CUDA:
    GPU: '0'
DATASET:
    IMAGE_SIZE:
        H: 640
        W: 640   # resized width: 160
    IMAGE_TRAIN_ROOT: "../data/detection/train/imgs"
    LABEL_TRAIN_ROOT: "../data/detection/train/gt"
    IMAGE_VAL_ROOT: "../data/detection/test/imgs"
    LABEL_VAL_ROOT: "../data/detection/test/gt"
TRAIN:
    EPOCH: 800
    BATCH: 4
    SHUFFLE: True
    WORKERS: 0
    RESUME:
        FLAG: False
        MODEL_SAVE_PATH: '/home/simple/mydemo/ocr_project/pytorch_psenet_project/pytorch_psenet/outputs/2020-09-11@21:39:28/model.pth'
    OPTIMIZER: 'adam'
    LR: 0.001
    SCHEDULER:
        IS_MultiStepLR: False #if True,the scheduler choice the multisteplr,if False,the scheduler choice the warmuplr
        MultiStepLR:
            LR_STEP: [4, 8]
            LR_FACTOR: 0.1
        WarnUpLR:
            milestones: [200, 400]
            gamma: 0.1
            warmup_factor: 0.1
            warmup_iters: 10
            warmup_method: "linear"
    SHOW_STEP: 10

VALID:
    BATCH: 1
    SHUFFLE: False
    WORKERS: 8
MODEL:
    NAME: 'PSENET'
    BACKBONE: 'resnet152'#['resnet18','resnet34','resnet50','resnet101','resnet152','densenet','mobilenet_v2','mobileNet_v3_Large','mobileNet_v3_Small']
    NUM_OUPUT: 256
    PRETRAINED: True
    MODEL_SAVE_DIR: 'outputs'
    PSE:
        n: 6
        m: 0.5
    LOSS:
        LAMBDA: 0.7
        OHEM:
          negation: 3
          position: 1


